#!/bin/sh

uci set network.globals.ula_prefix=""
uci commit network

uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

if [ "$(opkg list-installed | grep luci-app-passwall)" != "" ]; then
	# Add Passwall rules
	uci set passwall.PCR=shunt_rules
	uci set passwall.PCR.remarks="公主连结日服"
	uci set passwall.PCR.domain_list="api-priconne-redive.cygames.jp"
	uci set passwall.BILIBILI=shunt_rules
	uci set passwall.BILIBILI.remarks="哔哩哔哩动画"
	uci set passwall.BILIBILI.domain_list="bilibili.com
biliapi.net
bilivideo.com
bilivideo.cn"
	uci set passwall.UMA=shunt_rules
	uci set passwall.UMA.remarks="赛马娘"
	uci set passwall.UMA.domain_list="api-umamusume.cygames.jp"
	uci commit passwall
	echo "byr.pt" >> /usr/share/passwall/rules/proxy_host
fi

# Get self script
curl -s http://192.168.1.192:8080/script/download.sh -o /root/download.sh && chmod +x /root/download.sh

# Set allsign crontab
if [ -f /etc/config/allsign ]; then
	cangku=$(uci get allsign.cangku.cron)
	gmgard=$(uci get allsign.gmgard.cron)
	nginx=$(uci get allsign.nginx.cron)
	chmod +x /root/cangku.sh
	chmod +x /root/gmgard.sh
	chmod +x /root/update_cer.sh
	echo "$cangku" >>/etc/crontabs/root
	echo "$gmgard" >>/etc/crontabs/root
	echo "$nginx" >>/etc/crontabs/root
fi

# Enable IPv6
uci set dhcp.@dnsmasq[0].filter_aaaa='0'
uci commit dhcp

# Enable Vim xterm & mouse copy/paste
echo "export TERM=xterm" >>/etc/profile
sed -i "s/mouse=a/mouse=r/g" /usr/share/vim/vim*/defaults.vim

# Open HTTP and HTTPS port, reset nginx
if [ "$(opkg list-installed | grep luci-.*nginx)" != "" ]; then
	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='443'
	uci set firewall.@rule[-1].name='HTTPS'
	# [ -f /etc/jarao/flag ] && uci set firewall.@rule[-1].family='ipv6'

	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='80'
	uci set firewall.@rule[-1].name='HTTP'
	# [ -f /etc/jarao/flag ] && uci set firewall.@rule[-1].family='ipv6'
	
	uci commit firewall

	# use custom nginx conf
	# uci set nginx.global.uci_enable=false
	# uci commit nginx
fi
