#!/bin/sh

ULA_PREFIX='dead:2333:6666::/48'
[ -f /etc/jarao/flag ] && ULA_PREFIX=''

uci set network.globals.ula_prefix='$ULA_PREFIX'
uci commit network

uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# Open HTTP and HTTPS port
uci add firewall rule
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].name='HTTPS'
uci set firewall.@rule[-1].family='ipv6'

uci add firewall rule
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='80'
uci set firewall.@rule[-1].name='HTTP'
uci set firewall.@rule[-1].family='ipv6'

uci commit firewall

# Enable IPv6
uci set dhcp.@dnsmasq[0].filter_aaaa='0'
uci commit dhcp

cat >/etc/init.d/nginx <<EOF
#!/bin/sh /etc/rc.common

START=80

start() {
        [ -d /var/log/nginx ] || mkdir -p /var/log/nginx
        [ -d /var/lib/nginx ] || mkdir -p /var/lib/nginx
        [ -f /var/run/nginx.pid ] || touch /var/run/nginx.pid
        nginx -c /etc/nginx/nginx.conf
}

stop() {
        [ -f /var/run/nginx.pid ] && nginx -s stop
}

reload() {
        nginx -s reload
}

EOF

sed -i "/nginx/d" /etc/crontabs/root
/etc/init.d/nginx enable && /etc/init.d/nginx restart
