#!/bin/sh

# Permission
chmod 600 -R /etc/dropbear
chmod 600 -R /root/.ssh
chmod 644 -R /root/.ssh/*.pub
chmod 644 /root/.ssh/config
[ -d /root/.script ] && chmod -R 755 /root/.script/*.sh

# Script
if [ -d /root/.script ]; then
	# Set allsign crontab
	/root/.script/allsign.sh deploy
	# Init passwall
	/root/.script/passwall.sh
	# Set ip util
	ln -s /root/.script/ip.sh /usr/bin/ipip
	# Set backup util
	ln -s /root/.script/git-update.sh /usr/bin/opbk
fi

# Network
# Redirect DNS
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >>/etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >>/etc/firewall.user
# echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
# echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

# Enable IPv6
uci set dhcp.@dnsmasq[0].filter_aaaa='0'
uci commit dhcp

# Remove nat6 prefix
uci set network.globals.ula_prefix=""
uci commit network

# Open HTTP and HTTPS port, reset nginx
if [ -f /usr/sbin/nginx ]; then
	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='443'
	uci set firewall.@rule[-1].name='HTTPS'

	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='80'
	uci set firewall.@rule[-1].name='HTTP'

	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='4533'
	uci set firewall.@rule[-1].name='NM'

	uci add firewall rule
	uci set firewall.@rule[-1].target='ACCEPT'
	uci set firewall.@rule[-1].src='wan'
	uci set firewall.@rule[-1].proto='tcp'
	uci set firewall.@rule[-1].dest_port='2222'
	uci set firewall.@rule[-1].name='SSH'

	uci commit firewall

	sed -i "s/limit-as = 1000/limit-as = 20000/g" /etc/uwsgi/vassals/luci-webui.ini
	sed -i 's/fastpath[^_]/fastpath >\/dev\/null"/g' /usr/lib/lua/luci/controller/turboacc.lua
fi

# Theme
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# Enable Vim xterm & mouse copy/paste
echo "export TERM=xterm" >>/etc/profile
sed -i "s/mouse=a/mouse=r/g" /usr/share/vim/vim*/defaults.vim
