#!/bin/sh
case "$1" in
install)
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    ;;
init)
    which zsh && sed -i -- 's:/bin/bash:'$(which zsh)':g' /etc/passwd
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    grep -q '^# Revert root shell to bash if zsh is not available$' /etc/rc.local && exit 0
    zsh_revert="# Revert root shell to bash if zsh is not available
if grep -q '^root:.*:/usr/bin/zsh$' /etc/passwd && [ ! -x /usr/bin/zsh ]; then
    # zsh is root shell, but zsh was not found or not executable: revert to default bash
    [ -x /usr/bin/logger ] && /usr/bin/logger -s \"Reverting root shell to bash, as zsh was not found on the system\"
    sed -i -- 's:/usr/bin/zsh:/bin/bash:g' /etc/passwd
fi
"
    rc_ori=$(cat /etc/rc.local)
    cat >/etc/rc.local <<EOF
$zsh_revert
$rc_ori
EOF
    [ -f /root/.zshrc-bk ] && mv /root/.zshrc-bk /root/.zshrc && exec zsh -l
    ;;
*)
    echo "default (none of above)"
    ;;
esac
